apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ahmetbcakici-projects
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/ahmetbcakici/argocd-example
status: {}
